---

    - name: copy shared scripts
      template:
        src: "{{ item }}"
        dest: "{{ cloudwatch_user_home }}/bin/{{ item | basename }}"
        owner: "root"
        group: "root"
        mode: "0775"
      with_fileglob:
        - "../templates/*_shared.sh"

    - name: copy disk-free scripts
      template:
        src: "{{ item }}"
        dest: "{{ cloudwatch_user_home }}/bin/{{ item | basename }}"
        owner: "root"
        group: "root"
        mode: "0775"
      with_fileglob:
        - "../templates/*disk_free*.sh"



