---

    - name: set cronjob for s3 sync (s3->local dir)
      cron:
        name: "s3 sync for {{ target_s3_sync_dir }}"
        user: "{{ cronjob_owner | mandatory}}"
        special_time: daily
        state: present
        job: >
            /usr/bin/aws s3 sync
            "s3://{{ s3_sync_bucket_name }}/{{ s3_sync_prefix }}"
            "{{ target_s3_sync_dir }}"
            2>&1 | logger -t "[s3 sync]"

