---

    - name: gather ec2 facts
      ec2_metadata_facts:

    - name: copy shared script
      template:
        src: custom_metrics_shared.sh
        dest: "{{ script_install_dir }}/custom_metrics_shared.sh"
        owner: root
        mode: "0775"

    - name: copy disk-free script
      template:
        src: disk_free_metric.sh
        dest: "{{ script_install_dir }}/disk_free_metric.sh"
        owner: root
        mode: "0775"

    - name: set cronjob for disk space
      cron:
        name: "disk_metrics"
        user: "{{ cronjob_owner }}"
        minute: "*/5"
        state: present
        job: >
            {{ script_install_dir }}/disk_free_metric.sh "type ext|type xfs" 2>&1 | logger -t "[cloudwatch disk]

