---

    - name: set cronjob for disk space
      cron:
        name: "disk_metrics"
        user: "cloudwatch"
        minute: "*/5"
        state: present
        job: >
            {{ org_rootdir }}/bin/disk_free_metric.sh "type ext|type xfs" 2>&1 | logger -t info

    - name: set cronjob for webapp availability
      cron:
        name: "{{ service_name }}_availability"
        user: "cloudwatch"
        minute: "*/5"
        state: present
        job: >
            {{ org_rootdir }}/bin/{{ service_name }}_response_time_metric.sh 2>&1 | logger -t info
      when: "'tag_webserver' in group_names or 'tag_webserver_candidate' in group_names"
