---

    - name: set cronjob for disk space
      cron:
        name: "disk_metrics"
        user: "{{ cloudwatch_user }}"
        minute: "*/5"
        state: present
        job: >
            {{ cloudwatch_user_home }}/bin/disk_free_metric.sh "type ext|type xfs" 2>&1 | logger -t cloudwatch_disk_free

