---
    - name: create or fetch instance profile
      become: no
      local_action: >
        shell {{ role_path }}/files/create_instance_profile.sh
        {{ lookup('env', 'AWS_PROFILE') | default('default', true) }}
        {{ policy_document_path }} {{ permission_name }}
      register: policy_result

    - debug:
        var: policy_result

    - name: check for instance profile associations
      become: no
      local_action: |
        shell aws ec2 describe-iam-instance-profile-associations \
        --filters Name=instance-id,Values={{ hostvars[inventory_hostname].ec2_id }}
      register: assoc_result

    - set_fact:
        instance_profile_assoc: "{{ assoc_result.stdout | from_json }}"

    - name: debug profile associations
      debug:
          var: instance_profile_assoc

    - set_fact:
        has_instance_profile_name: "{% for ip in instance_profile_assoc.IamInstanceProfileAssociations %}\
                {% if instance_profile_name_for_cloudwatch in ip.IamInstanceProfile.Arn %}\
                  {{ ip.IamInstanceProfile.Arn | trim | basename }}\
                {% endif %}\
            {% endfor %}"

    - debug:
        var: has_instance_profile_name

    - name: associate instance profile to instance
      become: no
      local_action: |
          shell aws ec2 associate-iam-instance-profile \
          --instance-id {{ hostvars[inventory_hostname].ec2_id }} \
          --iam-instance-profile Name={{ permission_name }}_instance_profile
      when: "has_instance_profile_name is not defined or has_instance_profile_name == ''"
